### PR TITLE
Can't open an issue so I do this here (sorry)

### PR DESCRIPTION
**Pull request by vic1707**
The issue tab is inaccessible (or maybe I'm stupid) so I figured I'd simply open a dumb PR to contact you.

I'm trying out some new monospace fonts and came across your's and I love it.

But I can't get it to in monospace correctly in VSCode on some cases, looks like the `#` is the culprit.
I deliberately made the issue more visible with `letterSpacing: 4` but the 3 lines of comments are all the same number of characters as my terminal will attest.

I'm going crazy, do you know what I've done wrong, is this an issue with the font itself?

image
image

### CODE REVIEW

**Comment by kaBeech** [comment]
@vic1707 Haha no worries, whatever gets us connected! Sorry I didn't see this right away - I've been living under a rock tryna launch 1.0 on another project.

Huh, that's weird.

Just for clarity, the top screenshot is showing the error in VSC and the bottom one is showing it work correctly in Vim, is that right?

I'm seeing the same behavior on my machine. It's also easily apparent, even without the extra letter spacing, when highlighting the whole line (ignore the wonky vertical alignment in my screenshot - that's an artifact of my switch from Kubuntu/X11 to NixOS/Hyprland that I haven't gotten around to fixing yet.

VSC Serious:
VSC_Serious

Vim Serious:
Vim_Serious

What's even weirder is I'm not seeing the issue with Comic Shanns Mono, and we share the same '#' glyph. I didn't make any stylistic changes on that glyph in Serious and I don't think I edited them any differently. My guess is maybe Finii did something when they were doing optimizations on the Comic fork, or (less likely) it's an artifact of the processing Thai did on Comic Mono?

VSC Comic:
VSC_Comic

Not seeing anything at validation that would cause this (not sure what's up with that self-intersection in 'b' - I'll fix that when I get around to it, shouldn't cause any issues for now).

Validation:
validation

Not seeing any width issues either (though this makes me wonder if I should standardize the right and left bearings - I like the wonkiness for Comic but this might be an appropriate adjustment for Serious).

Number Sign Metrics:
metrics_number

W Metrics:
metrics_W

I'll take a deeper look soon. I've got a busy weekend but I've got an idea that I'll plan to try next week at the latest.

Thanks for letting me know, that's super strange. Thanks also for using the font, it always makes me happy to know that others are making good use of it 😸

**Comment by kaBeech** [comment]
#39

**Comment by vic1707** [comment]
Thank you for your quick response nonetheless (less than a month is fast to me on FOSS 😉).
Thank you for the explanation it's indeed quite strange, maybe it's a bug on VSCode side 🤷

I also stumbled upon another instance of that strange behavior involving the `*`

image
image

image
image

**Comment by kaBeech** [comment]
@vic1707 are you able to get to the Issue page I made by following this link (#39)? If so let's move further discussion of the issue over there. For now I'll reply here in case the link doesn't work.

Yeah, it might be a bug on VSC's side, but if it works for Comic Shanns Mono then it can work for Serious Shanns.

Huh. Curiouser and curiouser. So check this out - it's not just the '#' glyph. Every glyph I've tried subbing in gives the same issue:

serious_at
serious_i

That means the fix I had in mind to try won't work.

I'm also gonna have to eat my words about it probably not being something I did because the actual project I forked originally ([Comic Mono](https://github.com/dtinth/comic-mono-font), which hasn't been updated since then outside of its README) also behaves normally:

comic_number_sign

I'll have to investigate a little deeper...

Side note - are you noticing any weirdness with the capital letters in Italics at all? I had opened issues #40 (most noticeable) and #41, but looking at the 'P' and 'R' in your screenshot here and the Serious Shanns demo page (https://kabeech.github.io/serious-shanns/) it looks like that might be more related to my terminal emulator setup:

renders_correctly

Thanks again for your help! Since Serious Shanns isn't packaged in the official NerdFonts release and everything's slightly weird in NixOS (and I'm lazy) I hadn't been using Serious Shanns since I switched over, so I had no idea there were any issues!

**Comment by kaBeech** [comment]
Fixed locally:

serious-fixed

Has to do with the Em Size. FontForge throws a warning when generating an `.otf` file with an Em Size other than 1000, but everything seems to work fine with an Em Size of 2048. So I might switch to `.ttf`, or just keep using `.otf` and not worry about the unconventional Em Size. Either way I'll release a fix later tonight

**Comment by kaBeech** [comment]
Fixed in the newly-released Version 5.0.0

**Comment by kaBeech** [comment]
@all-contributors please add @vic1707 for bug reporting

**Comment by kaBeech** [comment]
Closing per discussion in #39. Thanks for all the help!

**Pull request closed without merging**
